### ISSUE TITLE
Polyfilling fetch breaks other libraries

### ISSUE THREAD

**Issue by luthfib** [Vermonster/fhir-kit-client#197]
## Expected Behavior

Importing this library should not cause in a Next.js App to crash.

## Actual Behavior

Next.js app crashes when this library is included because it polyfills fetch. This file https://github.com/Vermonster/fhir-kit-client/blob/3b36f30f29f5bbeac356feed0db6ce3be3eeb711/lib/http-client.js#L3 polyfills fetch. Next.js however relies on it not being polyfilled. Was able to fix it by doing the following in the repo https://github.com/luthfib/auth0-nextjs-repro/blob/fetch-issue/app/api/auth/%5Bauth0%5D/route.ts. 

I would propose to add a config flag that allows the polyfill behavior to not happen. 

## Steps to Reproduce the Problem

  1. Follow README.MD instructions as outlined in https://github.com/luthfib/auth0-nextjs-repro/tree/fetch-issue

## Specifications

Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000
Binaries:
  Node: 18.11.0
  npm: 8.19.2
  Yarn: N/A
  pnpm: 8.9.2
Relevant Packages:
  next: 13.5.6
  eslint-config-next: 13.5.5
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2

**Comment by taylorkle** [comment]
Thanks for the feedback! We are looking into this.

**Comment by taylorkle** [comment]
Hello @luthfib, I haven't been able to reproduce this issue using the repo you provided. I used the fetch branch, but updated the route.ts file to exclude the next response workaround like so: 

`import { handleAuth } from "@auth0/nextjs-auth0";`
`export const GET = handleAuth();`

I tried with both Node 18.11.0 (specified in your post) and 18.14.2 ( specified in your .nvmrc file). I am able to successfully login to the application with auth0. Would you mind providing further details about how you encountered the issue?

**Comment by luthfib** [comment]
Looking into it. I was able to reproduce first time, but second time it was fixed. I will try to create a Dockerfile in the repo to see if I can get a more consistent reproduction going.

**Comment by luthfib** [comment]
@taylorkle I have updated https://github.com/luthfib/auth0-nextjs-repro/tree/fetch-issue. I added a dockerfile that can be run and upated the README instructions. I can now reliably recreate the issue.

**Comment by taylorkle** [comment]
Thanks @luthfib! I'll take a look

**Comment by taylorkle** [comment]
Thanks @luthfib! I don't see the dockerfile and the last commit I see is from 11/2. Is there maybe a commit that you didn't push?

**Comment by luthfib** [comment]
@taylorkle oops should be there now

**Comment by taylorkle** [comment]
@luthfib I don't know that the cross-fetch/polyfill from fhir-kit-client is the issue here. I was eventually able to reproduce the error without docker and took the following steps to test:
1. Edit node_modules/fhir-kit-client in the repo you provided to remove the cross-fetch/polyfill import
2. Run `npx patch-package fhir-kit-client`
3. Confirm that the patch was successful by logging changes from fhir-kit-client and logging imported modules using require.cache
I still get the error `Error: No response is returned from route handler. Ensure you return a Response or a NextResponse in all branches of your handler.` despite confirmation that cross-fetch is not imported.

I wonder if the problem lies with Next.js polyfill instead. See this issue https://github.com/vercel/next.js/issues/10509#issuecomment-585831295

**Comment by luthfib** [comment]
Okay, we'll look at it internally. Very weird bug and hard to pinpoint the root cause. Thanks for looking into it!

**Comment by luthfib** [comment]
We were eventually able to resolve by patching out cross-fetch from the following library in our repo https://github.com/jasonkuhrt/graphql-request. Not to say that using cross fetch here (fhir client) won't cause us issues, but in our case we will probably just patch it in this package as well just to be sure. Thanks for all the help.
